data_ingestion:
  test_size: 0.2
  
feature_engineering:
  max_features: 3000

model_building:
  model_name: RandomForestClassifier  
  random_state: 2                   
  model_params:                     
    n_estimators: 25